language: python
python:
  - '3.6'
  - '3.7-dev'
services:
  - postgresql
  - redis-server
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - pip install -r requirements.txt
  # - cat "class Mixin(object):pass" >> .vEnv/Lib/site-packages/django_prometheus/models.py
script:
  - pytest
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
