language: python
python:
  - '3.7'
  - '3.6'
  - '3.5'
  - '3.7-dev'
services:
  - postgresql
  - redis-server
install:
  - pip install -r requirements.txt
  # - cat "class Mixin(object):pass" >> .vEnv/Lib/site-packages/django_prometheus/models.py
script:
  - pytest